services:
  redis:
    image: redis:8
    container_name: redis-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
    restart: always

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    depends_on:
      - redis
    ports:
      - "5540:5540"
    environment:
      - RI_AUTO_ACCEPT_EULA=YES
      - RI_TELEMETRY_ENABLED=FALSE
      - RI_REDIS_HOST=redis
      - RI_REDIS_PORT=6379
      - RI_REDIS_USERNAME=default
    restart: always
